name: ReportHub  

on: 
  workflow_dispatch:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: report-hub-exadel
  AZURE_WEBAPP_PACKAGE_PATH: "./report-hub-exadel"
  API_PROJECT_PATH: "src/ReportHub.Api"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.API_PROJECT_PATH }}/report-hub
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: report-hub
        path: ${{ env.API_PROJECT_PATH }}/report-hub

  unit-test:
    name: Unit Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  automated-api-tests:
    name: Integration Test
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Start API server
        run: |
          dotnet run --project ${{ env.API_PROJECT_PATH }} --urls=http://localhost:5027 &
          sleep 10
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/tests/ReportHub.IntegrationTests/Report Hub.json" --integration-id "178987-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 937aac94-c2d3-46f7-93ce-32d1d5db1fb5 --integration-id 178987

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: automated-api-tests

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: report-hub 
          path: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
